/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Mon Jun 26 14:11:24 2017. */

#include "simple.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SimpleMessage_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, SimpleMessage, request, request, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for SimpleMessage.request is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
